// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;
using System;

namespace Eleia.ML
{
    public class CodeDetector
    {
        private MLContext mlContext;
        private PredictionEngine<CodeDetectorModelInput, CodeDetectorModelOutput> predEngine;

        public CodeDetector()
        {
            mlContext = new MLContext();
            string modelPath = AppDomain.CurrentDomain.BaseDirectory + "MLModel.zip";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            predEngine = mlContext.Model.CreatePredictionEngine<CodeDetectorModelInput, CodeDetectorModelOutput>(mlModel);
        }

        public CodeDetectorModelOutput Predict(CodeDetectorModelInput input)
        {
            return predEngine.Predict(input);
        }
    }
}