// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML.Data;

namespace Eleia.ML
{
    public class ModelInput
    {
        [ColumnName("type"), LoadColumn(0)]
        public string Type { get; set; }

        [ColumnName("content"), LoadColumn(1)]
        public string Content { get; set; }
    }
}