// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML.Data;

namespace Eleia.ML
{
    public class ModelOutput
    {
        // ColumnName attribute is used to change the column name from
        // its default value, which is the name of the field.
        [ColumnName("PredictedLabel")]
        public string Prediction { get; set; }

        public float[] Score { get; set; }
    }
}